require 'Faker'

5.times.map do
  User.create!(username: Faker::Name.name, email: Faker::Internet.email, password: "123456789")
end


User.create(username: "Test User", email: "test@gmail.com", password: "123456789")


Trail.create(name: "San Francisco
Northern Waterfront", description:"Did you know that nearly the entire San Francisco bayfront is manmade? Beneath your feet lie abandoned ships, excavated hilltops, rotting piers and rubble dumped into the bay after the 1906 earthquake and fire. Above, you will find one of the world’s most inviting urban waterfronts. Beginning at iconic Fort Point under the Golden Gate Bridge, follow Marine Drive southeast along the water, passing the Warming Hut. A natural-surface trail hugs the shoreline through Crissy Field along restored wetlands and sand dunes. A paved path is available inland of the marsh along Mason Street. At the yacht harbor, follow the paved trail to the east and proceed as it meanders along the shoreline through Marina Green, or take the spur trail to the east and see if the eclectic wave organ will play for you. Climb the hill into historic Fort Mason, back down to equally historic Aquatic Park, and continue along the shoreline to Fisherman's Wharf. A gap in the Bay Trail at Fisherman’s Wharf means there are no bicycle lanes between Hyde and Powell streets. Head east past Pier 39, follow The Embarcadero promenade along the shoreline and stop at Pier 7 for views of the San Francisco-Oakland Bay Bridge, Treasure Island and Yerba Buena Island. Pass the magnificent Ferry Building, take a trot out to the end of Pier 14, and continue south under the Bay Bridge. The path curves along the edge of South Beach Harbor and follows the shoreline around AT&T Park, home of the San Francisco Giants baseball team. Watch an inning for free from the stadium’s public viewing area. The northern bayfront, as well as the city’s ocean shoreline, is almost enough time within the Golden Gate National Recreation Area, the first urban national park in the US. See card #11 for Treasure and Yerba Buena islands. Side Trip: Bike into Sausalito over the Golden Gate Bridge, see the sights, and then take the ferry back to Pier 41 in San Francisco. To access the Fort Baker Bay Trail from the east sidewalk of the bridge, use the stairs from the Vista Point parking lot and cross under the span.", map_img:"http://baytrail.org/wp-content/uploads/2015/11/1000-BAY-TRAIL-01-Map.png", distance: 10, terrain: "paved", difficulty: 1, elevation_incr: 66, elevation_decr: 315)

Trail.create(name:"Brisbane Lagoon to Bayside Park", description:"With San Bruno Mountain looming above, begin exploring northern San Mateo County at the Brisbane Lagoon along Sierra Point Parkway. The lagoon was a cove before Highway 101 was constructed, and it continues to support thriving bird and fish populations. Travel along bike lanes under the highway and follow the perimeter trail to Sierra Point, past the Brisbane Fishing Pier to the Brisbane and Sierra Point marinas. Continuing south along the edge of an office park, curve around Oyster Cove Marina, where old piers bear witness to a century of enterprise. Ships for World Wars I and II were built here, and piping was manufactured for the Hetch Hetchy, Grand Coulee, Shasta, and Folsom dams. The trail continues through Oyster Point Park and Oyster Point Marina, past San Bruno Point Park, the former site of one of the largest Chinese fishing camps on the bay, and across Colma Creek, spanned by a bicycle/ pedestrian bridge. The path continues adjacent to Airport Boulevard and along North Access Road. Visit an enjoyable trail loop around a bus service facility at Safe Harbor and a surprising place to view wildlife. On its western side, a vibrant marsh invites shorebirds and ducks to feed. The Bay Trail is not yet complete around San Francisco International Airport. Aspiring pilots will enjoy the best place to view airplane landings and takeoffs at Bayfront Park in Millbrae. From the park, follow the paved trail south as it parallels the shoreline, edged by hotels and businesses. Continue south past the Burlingame Bird 8: Plant Sanctuary. A trail gap in this area requires bicyclists and pedestrians to use Bayshore Highway for a short stretch. When you reach Bayside Park, you'll see lighted fields for soccer and baseball, a playground, a dog park and lawns. Across the street on the bay is a small public fishing shore.", map_img: "http://baytrail.org/wp-content/uploads/2015/11/500-BAY-TRAIL-03-Map.png", terrain: "paved & unfinished path", difficulty: 1, elevation_incr: 0, elevation_decr: 0, distance: 10)






